CREATE TABLESPACE PROJETO_FINAL_BD
DATAFILE 'C:\Users\Alex Costa\Desktop\SQL_Fatec\ProjetoFatec\PROJETO_FINAL_BD.dbf' SIZE 10M 
AUTOEXTEND ON;

CREATE USER USER_PROJETO_FINAL
IDENTIFIED BY aluno
DEFAULT TABLESPACE PROJETO_FINAL_BD
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON PROJETO_FINAL_BD;

GRANT DBA TO USER_PROJETO_FINAL WITH ADMIN OPTION;

