/* TRIGGER HISTORICO TRANSACAO_EMPRESA*/
CREATE OR REPLACE TRIGGER HISTORICO_TRANSACAO_EMPRESA
BEFORE UPDATE OR DELETE ON TRANSACAO_EMPRESA FOR EACH ROW
BEGIN
INSERT INTO HISTORICO_TRANSACAO_EMPRESA VALUES(SYSDATE, USER, : OLD.TRAEMP_ID, : OLD.TRAEMP_DESCRICAO, : OLD.TRAEMP_TIPOTRANSACAO, : OLD.TRAEMP_VALORBRUTO, : OLD.TRAEMP_VALORLIQUIDO, : OLD.TRAEMP_DATATRANSACAO, : OLD.TRANS_ID, : OLD.EMP_ID, : OLD.USU_ID);
END;

/* TRIGGER HISTORICO TIPO FUNCAO*/
CREATE OR REPLACE TRIGGER HISTORICO_TIPO_FUNCAO
BEFORE UPDATE OR DELETE ON TIPO_FUNCAO FOR EACH ROW
BEGIN
INSERT INTO HISTORICO_TIPO_FUNCAO VALUES(SYSDATE, USER, : OLD.FUNCAO_ID, : OLD.FUNCAO_DESCRICAO, : OLD.FUNCAO_SALARIO, : OLD.EMP_ID, : OLD.TIP_SETORID);
END;

/* TRIGGER HISTORICO DE SENHAS */


CREATE OR REPLACE TRIGGER HISTORICO_SENHA
BEFORE UPDATE ON USUARIO
FOR EACH ROW
BEGIN
IF : NEW.SENHA <> : OLD.SENHA THEN
DELETE HISTORICO_SENHA H WHERE H.ID = : OLD.ID AND H.TIMESTAMP = (SELECT MIN(TIMESTAMP)FROM HISTORICO_SENHA U WHERE U.ID = : OLD.ID HAVING COUNT(*) >= 6);)
INSERT INTO HISTORICO_SENHA(USU_ID, TIMESTAMP, SENHA)VALUES(: OLD.ID, SYSDATE, : OLD.SENHA);
END IF;
END;