DROP TABLE TRANSACAO_EMPRESA;
DROP TABLE TRANSACAO;
DROP TABLE FUNCAO_FUNC;
DROP TABLE FUNCIONARIO;
DROP TABLE TIPO_FUNCAO;
DROP TABLE TIPO_SETOR;
DROP TABLE SOCIO;
DROP TABLE ALUNO;
DROP TABLE TELEFONE_EMPRESA;
DROP TABLE ENDERECO_EMPRESA;
DROP TABLE EMPRESA;
DROP TABLE TELEFONE;
DROP TABLE ENDERECO; 
DROP TABLE USUARIO;
drop table funcao;


CREATE TABLE USUARIO (
    USU_ID NUMBER NOT NULL  PRIMARY KEY,
    USU_CPF VARCHAR2(15) NOT NULL,
    USU_RG VARCHAR2(15) NOT NULL,
    USU_EMAIL VARCHAR2(200) NOT NULL,
    USU_NOME VARCHAR2(200) NOT NULL,
    USU_SENHA VARCHAR2(20) NOT NULL
);

CREATE TABLE ENDERECO (
    END_ID NUMBER NOT NULL  PRIMARY KEY,
    USU_ID NUMBER NOT NULL,
    END_CEP VARCHAR2(10) NOT NULL,
    END_LOGRADOURO VARCHAR2(150) NOT NULL,
    END_NUMERO NUMBER,
    END_COMPLEMENTO VARCHAR2(50),
    END_CIDADE VARCHAR2(150) NOT NULL,
    END_ESTADO VARCHAR2(100) NOT NULL,
    END_BAIRRO VARCHAR2(100) NOT NULL
);
ALTER TABLE ENDERECO ADD  FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID);



CREATE TABLE TELEFONE (
    TEL_ID NUMBER NOT NULL PRIMARY KEY,
    USU_ID NUMBER NOT NULL,
    TEL_DDD NUMBER NOT NULL,
    TEL_NUMERO VARCHAR2(10) NOT NULL
);
ALTER TABLE TELEFONE ADD FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID);

CREATE TABLE EMPRESA (
    EMP_ID NUMBER NOT NULL PRIMARY KEY,
    EMP_CNPJ VARCHAR2(20) NOT NULL,
    EMP_INCRICAO_MUNICIPAL VARCHAR2(25) NOT NULL,
    EMP_INCRICAO_ESTADUAL VARCHAR2(25) NOT NULL,
    EMP_NOME_FANTASIA VARCHAR2(150) NOT NULL,
    EMP_RAZAO_SOCIAL VARCHAR2(200) NOT NULL
);


CREATE TABLE ENDERECO_EMPRESA (
    EMPEND_ID NUMBER NOT NULL  PRIMARY KEY,
    EMP_ID NUMBER NOT NULL,
    EMPEND_CEP VARCHAR2(10) NOT NULL,
    EMPEND_LOGRADOURO VARCHAR2(150) NOT NULL,
    EMPEND_NUMERO NUMBER,
    EMPEND_COMPLEMENTO VARCHAR2(50),
    EMPEND_CIDADE VARCHAR2(150) NOT NULL,
    EMPEND_ESTADO VARCHAR2(100) NOT NULL,
    EMPEND_BAIRRO VARCHAR2(100) NOT NULL,
    EMPEND_EMAIL VARCHAR2(200),
    EMPEND_SITE VARCHAR2(200)
);
ALTER TABLE ENDERECO_EMPRESA ADD  FOREIGN KEY (EMP_ID) REFERENCES EMPRESA(EMP_ID);

CREATE TABLE TELEFONE_EMPRESA (
    EMPTEL_ID NUMBER NOT NULL PRIMARY KEY,
    EMP_ID NUMBER NOT NULL,
    EMPTEL_DDD NUMBER NOT NULL,
    EMPTEL_NUMERO VARCHAR2(20) NOT NULL
);
ALTER TABLE TELEFONE_EMPRESA ADD  FOREIGN KEY (EMP_ID) REFERENCES EMPRESA(EMP_ID);


CREATE TABLE ALUNO(
    ALU_RA NUMBER NOT NULL PRIMARY KEY,
    USU_ID NUMBER NOT NULL,
    EMP_ID NUMBER NOT NULL
);
ALTER TABLE ALUNO ADD FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID);
ALTER TABLE ALUNO ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);

CREATE TABLE SOCIO (
    SOC_ID NUMBER NOT NULL PRIMARY KEY,
    USU_ID NUMBER NOT NULL,
    EMP_ID NUMBER NOT NULL
);
ALTER TABLE SOCIO ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE SOCIO ADD FOREIGN KEY (USU_ID) REFERENCES USUARIO (USU_ID);

CREATE TABLE TIPO_SETOR (
    TIP_SETORID NUMBER NOT NULL PRIMARY KEY,
    TIP_DESCRICAO VARCHAR2(100) NOT NULL,
    EMP_ID NUMBER NOT NULL
);
ALTER TABLE TIPO_SETOR ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);

CREATE TABLE TIPO_FUNCAO (
    FUNCAO_ID NUMBER NOT NULL PRIMARY KEY,
    FUNCAO_DESCRICAO VARCHAR2(100) NOT NULL,
    FUNCAO_SALARIO NUMBER(10,2) NOT NULL,
    EMP_ID NUMBER NOT NULL, 
    TIP_SETORID NUMBER NOT NULL

);
ALTER TABLE TIPO_FUNCAO ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE TIPO_FUNCAO ADD FOREIGN KEY (TIP_SETORID) REFERENCES TIPO_SETOR (TIP_SETORID);


CREATE TABLE FUNCIONARIO (
    FUN_ID NUMBER NOT NULL PRIMARY KEY,
    FUN_CTPS VARCHAR2(20) NOT NULL, 
    USU_ID NUMBER NOT NULL,    
    EMP_ID NUMBER NOT NULL
);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID);

CREATE TABLE FUNCAO_FUNC(
    FUN_ID NUMBER NOT NULL,
    FUNCAO_ID NUMBER NOT NULL,
    EMP_ID NUMBER NOT NULL
);
ALTER TABLE FUNCAO_FUNC ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE FUNCAO_FUNC ADD FOREIGN KEY (FUN_ID) REFERENCES FUNCIONARIO(FUN_ID);
ALTER TABLE FUNCAO_FUNC ADD FOREIGN KEY (FUNCAO_ID) REFERENCES TIPO_FUNCAO(FUNCAO_ID);

CREATE TABLE TRANSACAO (
    TRANS_ID NUMBER NOT NULL PRIMARY KEY,
    TRANS_DESCRICAO VARCHAR2(100) NOT NULL,
    TRANS_DATA DATE,
    EMP_ID NUMBER NOT NULL
); 
ALTER TABLE TRANSACAO ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);



CREATE TABLE TRANSACAO_EMPRESA (
    traEmp_id NUMBER NOT NULL Primary key,
    traEmp_descricao VARCHAR2(100) NOT NULL,
    traEmp_tipoTransacao VARCHAR2(100) NOT NULL,
    traEmp_valorBruto NUMBER(8,2) NOT NULL,
    traEmp_valorLiquido NUMBER(8,2) NOT NULL,
    traEmp_dataTransacao DATE,
    trans_id NUMBER NOT NULL,
    emp_id NUMBER NOT NULL ,
    usu_id NUMBER NOT NULL 
);
ALTER TABLE TRANSACAO_EMPRESA ADD FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE TRANSACAO_EMPRESA ADD FOREIGN KEY (TRANS_ID) REFERENCES TRANSACAO (TRANS_ID);
ALTER TABLE TRANSACAO_EMPRESA ADD FOREIGN KEY (USU_ID) REFERENCES USUARIO (USU_ID);
