/* LISTAR ALUNOS DE UMA DETERMINADA EMPRESA */
SELECT 
ALUNO.ALU_RA AS RA, 
USUARIO.USU_NOME AS ALUNO, 
EMPRESA.EMP_NOME_FANTASIA AS EMPRESA 

FROM ALUNO, USUARIO, EMPRESA 

WHERE 
ALUNO.EMP_ID = 2020060001 AND
USUARIO.USU_ID = ALUNO.USU_ID AND
EMPRESA.EMP_ID = ALUNO.EMP_ID;

/* LISTAR FUNCIONARIOS DE UMA DETERMINADA EMPRESA */

SELECT 
USU.USU_NOME AS FUNCIONARIO, 
EMP.EMP_NOME_FANTASIA AS EMPRESA,
TF.FUNCAO_DESCRICAO AS FUNCAO

FROM 
FUNCIONARIO FUN, 
USUARIO USU, 
EMPRESA EMP, 
FUNCAO_FUNC FF, 
TIPO_FUNCAO TF

WHERE 
FUN.USU_ID = USU.USU_ID AND
FUN.EMP_ID = 2020060001 AND
EMP.EMP_ID = FUN.EMP_ID AND
FF.EMP_ID = EMP.EMP_ID AND
FF.FUN_ID = FUN.FUN_ID AND
FF.FUNCAO_ID = TF.FUNCAO_ID;